### ISSUE TITLE
Problem installing the DAL2 SPA module

### ISSUE THREAD

**Issue by timvdh** [ChrisHammond/DNNTemplates#75]
Anybody know if this modules still works with the latest DNN version? My site gives a 503 error (see exception below) once I try to load the site with the newly installed module that uses the SPA DAL2 with DNN 9.20.02. The site works again, when I delete the module DLL from the bin directory of the DNN installation.

I think I installed it right, I also tried the Windows Forms Version and that worked. I think there is no specific video about the SPA module template. When I attach the debugger I get a ThreadAbortException.

2022-03-25 22:45:51,927 [HPZ220][Thread:28][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="An error has occurred." ctrl="ASP.admin_menus_moduleactions_moduleactions_ascx" exc="System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Admin.Containers.ModuleActions.OnLoad(EventArgs e) in D:\a\1\s\DNN Platform\Website\admin\Menus\ModuleActions\ModuleActions.ascx.cs:line 101"
2022-03-25 22:45:52,001 [HPZ220][Thread:28][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The control collection cannot be modified during DataBind, Init, Load, PreRender or Unload phases.
   at System.Web.UI.ControlCollection.RemoveAt(Int32 index)
   at System.Web.UI.ControlCollection.Clear()
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls() in D:\a\1\s\DNN Platform\Library\UI\Modules\ModuleHost.cs:line 140
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

**Comment by ChrisHammond** [comment]
For your Spa module are you putting it into the proper directory path?

**Comment by timvdh** [comment]
I used \DesktopModules\MyModule - which is probably wrong?

**Comment by ChrisHammond** [comment]
That should be right as long as you make sure it is in that directory, not one level below that.

Other things to check:

in IIS, go to the DesktopModules folder and see if it got turned into a VirtualDirectory, if so, right click and choose delete/remove. Check the MyModule folder for the same

**Comment by ChrisHammond** [comment]
I was able to create a brand new SPA module in a DNN 9.10.1 instance this evening without any problems.

**Comment by timvdh** [comment]
Thanks a lot for your effort, Chris. And for the great templates, btw. I am using the same installation that I have upgraded for 15 years or so, I probably have to do a fresh install.
