### ISSUE TITLE
Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout)

### ISSUE THREAD

**Issue by abuhmead1987** [ChrisHammond/DNNTemplates#8]
I created a DNN module using the template V5, I deleted all things in the module which needed Database, I need to create a grid view depending on Stored procedure, so, I deleted all files but skipped the following before start coding
![91](https://cloud.githubusercontent.com/assets/1290291/10658313/47734bf6-789e-11e5-9ef1-101677d4510b.PNG)

When I build it and install it no problems, But when I add the module to the page the module doesn't appears on the page, I saw the following error from Event Viewer 

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:345e0e42-0a77-4ba7-b367-5b0af2b8f84a
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:p8RIg/GOUntOzmRWQ/by2A==
Message:Lock obtain timed out: NativeFSLock@C:\inetpub\wwwroot\moheportal_uptodate\App_Data\Search\write.lock
StackTrace:
   at Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout)
   at Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, MaxFieldLength mfl)
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.get_Writer()
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.Delete(Query query)
   at DotNetNuke.Services.Search.Internals.InternalSearchControllerImpl.DeleteSearchDocumentInternal(SearchDocument searchDocument, Boolean autoCommit)
   at DotNetNuke.Services.Search.SearchEngine.DeleteRemovedObjects()
   at DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()
InnerMessage:
InnerStackTrace:
Source:Lucene.Net
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: cid-mah

**Comment by WillStrohl** [comment]
Try deleting everything from your App_Data/Search folder and reloading the page. Backup those files first, just in case. I'm not sure this is a problem with the template.

**Comment by ChrisHammond** [comment]
This isn't a template issue.
